package main;

import model.Admin;
import model.House;
import model.Landlord;
import model.Student;

public class HomeSweetMain {
    public static void main(String[] args) {

        // 1. Create Admin
        Admin a1 = new Admin("John Doe", "johndoe@gmail.com", "password123!"); 
        
        // 2. Create Landlords
        Landlord l1 = new Landlord("Elizabeth", "123-456-7890", "abc123@gmail.com", "Phnom Penh");
        Landlord l2 = new Landlord("Rose", "123-456-7890", "rose@gmail.com", "Phnom Penh");

        // 3. Create Students
        Student s1 = new Student("Jane Smith", "janesmith@gmail.com", "987-654-3210", "studentpassword@", "Contract A", "1234567890123");
        Student s2 = new Student("Michael Brown", "michael@gmail.com", "987-654-3210", "studentpassword@", "Contract B", "1234567890124");
    
        // 4. Create Houses (Pass the Landlord OBJECT, not a String)
        House h1 = new House("123 Main St", l1, true, 500.00);
        House h2 = new House("456 Oak Ave", l2, true, 600.00);

        // 5. Register data into Admin's system
        a1.addLandlord(l1);
        a1.addLandlord(l2);

        a1.addStudent(s1);
        a1.addStudent(s2);

        a1.addHouse(h1);
        a1.addHouse(h2);

        // --- DEMONSTRATION ---
        
        System.out.println("--- INITIAL STATE ---");
        a1.viewHouses();
        a1.viewStudents();
        a1.viewLandlords();

        System.out.println("\n--- PROCESSING RENTAL ---");
        // Use a1 (the admin we created) to process the rental
        a1.createRentalAgreement(s1, h1, "2023-10-01", "2024-10-01");
        a1.createRentalAgreement(s2, h2, "2023-11-01", "2024-11-01");

        System.out.println("\n--- UPDATED STATE ---");
        a1.viewHouses(); // House 1 will now be unavailable
        a1.viewAllPayments(); // Shows the payment generated by the agreement
    }
}